korp_backend_url: https://DELIBERATELY.INVALID
languages:
  - value: sme
    label: Davvisámi
  - value: nob
    label: Norsk
  - value: fin
    label: Suomi
  - value: eng
    label: English
has_timespan: false

# anders: autocomplete is currently hard-coded to really only work for
# språkbanken's systems
autocomplete: false

default_options:
  is: '='
  is_not: '!='
  starts_with: '^='
  contains: '*='
  ends_with: '&='
  matches: '*='
  matches_not: '!*='
